In [15]:
import torch
import torch.nn.functional as F
import time

# Create a 2x2 tensor (image)
image = torch.tensor([[1., 2.],
                      [3., 4.]])

print(image)

tensor([[1., 2.],
        [3., 4.]])


In [5]:
# nearest neighbor interpolation
start = time.time()
for i in range(5000):
    output = F.interpolate(image[None, None, :, :], scale_factor=2, mode='nearest')
end = time.time()
print(f"Execution time: {end - start:.4f} seconds")
print(output)

Execution time: 0.0376 seconds
tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])


In [16]:
# nearest neighbor interpolation
output = F.interpolate(image[None, None, :, :], scale_factor=2, mode='bilinear', antialias=True)
print(output)

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])


In [17]:
# bilinear interpolation
output = F.interpolate(image[None, None, :, :], scale_factor=2, mode='bilinear')
print(output)

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])


In [10]:
# bilinear interpolation
output = F.interpolate(image[None, None, :, :], scale_factor=2, mode='bilinear', align_corners=False)
print(output)

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])


In [13]:
# bilinear interpolation
output = F.interpolate(image[None, None, :, :], scale_factor=2, mode='bicubic', align_corners=False)
print(output)

tensor([[[[0.6836, 1.0156, 1.5625, 1.8945],
          [1.3477, 1.6797, 2.2266, 2.5586],
          [2.4414, 2.7734, 3.3203, 3.6523],
          [3.1055, 3.4375, 3.9844, 4.3164]]]])


In [14]:
# bilinear interpolation
output = F.interpolate(image[None, None, :, :], scale_factor=2, mode='bicubic', antialias=True)
print(output)

tensor([[[[0.7353, 1.0307, 1.6164, 1.9118],
          [1.3261, 1.6214, 2.2071, 2.5025],
          [2.4975, 2.7929, 3.3786, 3.6739],
          [3.0882, 3.3836, 3.9693, 4.2647]]]])


In [1]:
def get_gaussian_kernel(kernel_size=5, sigma=1.0, channels=3):
    # 1D Gaussian
    x = torch.arange(kernel_size).float() - kernel_size // 2
    gauss = torch.exp(-x**2 / (2 * sigma**2))
    gauss = gauss / gauss.sum()
    
    # 2D Gaussian Kernel
    kernel2d = gauss[:, None] @ gauss[None, :]
    kernel2d = kernel2d.expand(channels, 1, kernel_size, kernel_size)
    return kernel2d

In [ ]:
channels = x.shape[1]
kernel = get_gaussian_kernel(3, 1.0, channels).to(x.device)
padding = kernel_size // 2
x_blur = F.conv2d(x, kernel, padding=padding, groups=channels)